openapi: '3.0.2'
info:
  title: Тестовое занание для Shakuro
  version: '1.0'
servers:
  - url: https://localhost:3080/api
paths:
  /publishers:
    get:
      summary: Получение списка издателей
      description: Возвращает всех издателей, чисто для получения ЧПУ издателя, чтобы посмотреть магазины
      tags:
        - "Издатели"
      responses:
        '200':
          $ref: '#/components/responses/Publishers'
  /publishers/{slug}:
    get:
      summary: Получение списка магазинов, которые продают книги этого издателя
      tags:
        - "Магазины"
      parameters:
        - in: path
          name: slug
          required: true
          description: ЧПУ издателя
          schema:
            type: integer
          example: amazon
      responses:
        '200':
          $ref: '#/components/responses/Operations'

  /shops{id}/order:
    post:
      summary: Создание новго заказа
      tags:
        - "Магазины"
      requestBody:
        $ref: '#/components/requestBodies/CreateOrder'
      responses:
        '201':
          $ref: '#/components/responses/Order'
        '400':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Publisher:
      type: object
      properties:
        id:
          type: integer
          example: 1
          description: ID издателя
        name:
          type: string
          example: O'Reilly
          description: Название издателя
        url:
          type: string
          description: URL для просмотра магазинов, которые продают книги этого издателя
          example: "/api/publishers/o-reilly-media"

    Error:
      type: object
      properties:
        status:
          type: integer
          description: HTTP-статус ошибки
          example: 400
        title:
          type: string
          description: Заголовок ошибки
          example: Ошибка валидации
        message:
          type: string
          description: Сообщение ошибки
          example: На складе не осталось книг

  requestBodies:
    CreateOrder:
      description: Данные для создания новой операции
      content:
        application/json:
          schema:
            type: object
            properties:
              book_id:
                type: integer
                description: ID книги
                example: 1
              amount:
                type: integer
                description: Количество книг к заказу
                example: 2

  responses:
    Publishers:
     description: OK
     content:
       application/json:
        schema:
          type: array
          items: 
            $ref: '#/components/schemas/Publisher'
    
    Order:
     description: OK
     content:
       application/json:
        schema:
          type: object
          properties:
            shops:
              type: object
              properties:
                order_id:
                  type: integer
                  example: 1
                  description: ID заказа
                shop:
                  type: string
                  example: Amazon
                  description: название магазина
                book:
                  type: string
                  example: Freehold War
                  description: название книги
                amount:
                  type: integer
                  example: 2
                  description: Количество заказанных книг
    Operations:
     description: OK
     content:
       application/json:
        schema:
          type: object
          properties:
            shops:
              type: object
              properties:
                id:
                  type: integer
                  example: 1
                  description: ID магазина
                name:
                  type: string
                  example: Amazon
                  description: Название магазина
                books_sold_count:
                  type: integer
                  example: 10
                  description: Общее количество проданных книг
                books_in_stock:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                        description: ID книги
                      title:
                        type: string
                        description: Название книги
                        example: Freehold War
                      copies_in_stock:
                        type: integer
                        description: Количество книг на складе
                        example: 12

    Errors:
     description: OK
     content:
       application/json:
        schema:
          type: object
          properties:
            errors:
              type: array
              items:
                $ref: '#/components/schemas/Error'
      